#!/bin/bash

# _GOPATH=$GOPATH

# function em() {
#    emacsclient -n $1
# }

# function emc() {
#    emacsclient -n -c $1
# }

# function flux() {
#     xflux -l 58 -g 13
# }

# function gopath_old {
#   export GOPATH=$_GOPATH:`pwd`
#   export GOPATH=$_GOPATH:`pwd`:`pwd`/vendor
#   echo "Setting GOPATH to $GOPATH"
# }

# function gopath {
#   export GOPATH=`pwd`
#   export GO15VENDOREXPERIMENT=1
#   echo "Setting GOPATH to $GOPATH"
# }

# function update_gotools {
#   echo "gocode"
#   go get -u github.com/nsf/gocode
#   echo "goimports"
#   go get -u golang.org/x/tools/cmd/goimports
#   echo "oracle"
#   go get -u golang.org/x/tools/cmd/oracle
#   echo "gb"
#   go get -u github.com/constabulary/gb/...
#   echo "protobuf"
#   go get -u github.com/golang/protobuf/{proto,protoc-gen-go}
#   echo "godep"
#   go get -u github.com/tools/godep
#   echo "gogo protobuf"
#   go get -u github.com/gogo/protobuf/proto
#   go get -u github.com/gogo/protobuf/protoc-gen-gogo
#   go get -u github.com/gogo/protobuf/gogoproto
#   echo "govendor"
#   go get -u github.com/kardianos/govendor
#   echo "godef"
#   go get -u github.com/rogpeppe/godef
# }

function install_gcloud {
  curl https://sdk.cloud.google.com | bash -s -- --disable-prompts --install-dir="$HOME/.local"
}

function install_helm {
  curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
}

function install_minikube {
  curl -Lo /tmp/minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x /tmp/minikube && mv /tmp/minikube $HOME/.local/bin/
}

function install_kubernetes {
  curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o ~/.local/bin/kubectl &&
    chmod +x ~/.local/bin/kubectl
}

function install_skaffold {
  curl -Lo ~/.local/bin/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 &&
    chmod +x ~/.local/bin/skaffold
}

# function install_virtualbox {
#     echo "deb http://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list > /dev/null \
#         && wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add - \
#         && sudo apt update \
#         && sudo apt install dkms virtualbox-5.1
# }

function install_dockercompose {
  local version="1.16.1"
  sudo curl -L "https://github.com/docker/compose/releases/download/$version/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  sudo chmod +x /usr/local/bin/docker-compose
  sudo curl -L "https://raw.githubusercontent.com/docker/compose/$version/contrib/completion/bash/docker-compose" -o /etc/bash_completion.d/docker-compose
}

function install_ohmyposh {
  curl -s https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin
}

function install_krew {
  (
    set -x
    cd "$(mktemp -d)" &&
      OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
      ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
      KREW="krew-${OS}_${ARCH}" &&
      curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
      tar zxvf "${KREW}.tar.gz" &&
      ./"${KREW}" install krew
  )
}

function install_lazygit {
  LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*')
  curl -Lo /tmp/lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
  tar xf /tmp/lazygit.tar.gz /tmp/lazygit
  install /tmp/lazygit $HOME/.local/bin
}

function install_nvim {
  curl -Lo /tmp/nvim-linux64.tar.gz "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
  tar -C $HOME/.local -zxf /tmp/nvim-linux64.tar.gz
  ln -sfv $HOME/.local/nvim-linux64/bin/nvim $HOME/.local/bin/nvim
  ln -sfv $HOME/.local/nvim-linux64/bin/nvim $HOME/.local/bin/vim
  ln -sfv $HOME/.local/nvim-linux64/bin/nvim $HOME/.local/bin/vi
  rm /tmp/nvim-linux64.tar.gz
}

function preview_themes {
  for file in ~/.poshthemes/*.omp.json; do
    echo "$file\n"
    oh-my-posh --config $file --shell universal
    echo "\n"
  done
}

function klog {
  format='{{color .PodColor .PodName}} {{with $d := .Message | parseJSON}}{{ index ($d) "@timestamp"}} {{$d.level}} | {{$d.logger_name}} | {{$d.message}}{{if $d.stack_trace}}{{"\n"}}{{$d.stack_trace}}{{end}}{{end}}{{"\n"}}'
  kubectl stern $1 --template="$format"
}
